language: node_js
node_js:
- iojs
before_deploy: npm run-script prepublish
deploy:
  - provider: npm
    email: jacob@jacobgreenleaf.com
    api_key:
        secure: XuZ72fDeHHojBI/SJVCh40b7GW7mKrg13+b9dX/XA7fT1mxqaCqx9BoyCWPIOBwzyhiQA0pE5vu1r3bTffbPhdJRb0IswFAgbnJyFRTkUT1vlCZk+1AUTQRFAbikojta75qqifG19H4yupSmYSDa3WSuOfpwD6fHsXUL6UjAZ8TDXiZY9eqyBdaRAymveh68aKslk+1z6k8AWbUcBTBXhWz0KACp0tJyFTmtZ/trosD7Jm94KryhF8fCRLr3rgho2vLqCrDo0MOaAl6p1uN+PIEsmXANRjoD5NPRb0z6tREI16E58kBh6l2wfuHT9S0BAENhnvvapUmWa0wJ9q8PLqSJ3EynFUlISgaUutwm9M2lbRRTiJIUF6QqsJI1+r8311Xa639In+qomq40lNdaV6wgbDHUA81F6QEKNgPJbfY5SlrWf9fmb0cGh3HkLh0MpjnLcDXR3Rjl+URZiisJj7CfwsQtmo5lQca7CdDYw8t6EFro2nGIORdVG6f9CTdNL3CLQS8SimnXNViJZuhjVpEgdHY4VJtOuv+hOCD/O0Q2HrgRUBcokUWGUyF+T4jf/xHtqw+HOmvYeNkdedxFBNIUqOay3AxeygMEMeoWQuC6ZXx5XssPYgqBkAPWiKjoDYgc2v0QxUNbnzhmu6PkZQ9SGfT6hR0h7Y8FMvyrMj8=
    on:
      tags: true
  - provider: releases
    api_key: 
        secure: adYUWchzu62jAkoISGizsgZH99CttnUUD6jfKWyUtpjXyRY148Ie1JgKzwb9DGu8do8PTqF5R5yPXgK6Vw7LwJiMYKO+SEVDiaHXNsdKkm4O4B44DNqojMMbBHX9fJPhI4I2Coo+8r9yOgzKieqf/+WuyOPJZ12/9/Vntj4xSJEwDUvaYkWOhLMXZbMQldc3z/H7gWz8JLbCBfc4C7hPIh35u4v552H4J6htHoTnhfgtXgpO2Tn3o+Ggkh84KNEInE4Fj9GAZDpJ0QIUtLUmt1a/dUw6YGA5C0hf9OBhUjC94QHSrbmoQkMR9gLPwAU0ii56wHoHM2mharmpnp4QaG/BznRQB422IHlKgEcd+oY31a0XMgIAq2/g3/HuVrCHiZQlsdWorZ5OpNVe6TP9ctNOndwJ3ZcoXsV3BAAOWkfu8ErqbKP+IVi83o5dMdeATgq0/2qL28tG/Nri+DnC+yzeib+xga+RPav19QAXfHYqDevBzFqswd4i8vupJ5bxYkWaXziy9Wag3Neti/IMkbYTSIaSg8R/0sXNkZW3CoWSpySOOmPBGFJnzTakZjeA5qQCcF2+TRNCEO8YcBlxFJH8FQjjGOcdg+x0JsZy4kpR6ACsNDcXHH8J3zUlDx+Jaj0uzY+nL9g4dtON5YpvGUdDw7HXCCSOPTC/8/iyBYA=
    file: "dist/incus.min.js"
    skip_cleanup: true
    on: 
      tags: true

